### ISSUE TITLE
Favicon not working

### ISSUE THREAD

**Issue by craph** [hendisantika/springboot-adminlte3-template#3]
Hi,
The code about the favicon is not working and have a wrong reference package. 
https://github.com/hendisantika/springboot-adminlte3-template/blob/main/src/main/java/com/hendisantika/config/FaviconConfiguration.java#L41
Best regards,

**Comment by craph** [comment]
From Spring Boot 2.2+ favicon is only taken from static resources: https://docs.spring.io/spring-boot/docs/2.3.9.RELEASE/reference/htmlsingle/#boot-features-spring-mvc-favicon

**Comment by hendisantika** [comment]
Can You send me PR for that @craph ?

**Comment by hendisantika** [comment]
I already bugfix the favicon but still not working. Can You send me your PR @craph ?

**Comment by hendisantika** [comment]
It's working now

**Comment by craph** [comment]
I can't see the favicon on my browser. Seems not working

**Comment by hendisantika** [comment]
It's working on my local...

**Comment by craph** [comment]
It's working in Firefox not in Brave. I'll try to find why it's not working :)
