### ISSUE TITLE
GitHub actions failed on some unit tests

### ISSUE THREAD

**Issue by craph** [hendisantika/springboot-adminlte3-template#4]
Hello @hendisantika ,

It looks like there are some issues in GitHub actions about tests. Did you seen it ?
https://github.com/hendisantika/springboot-adminlte3-template/runs/6898159474?check_suite_focus=true

It looks like the test part about Hikari is not correctly working

what this code does : https://github.com/hendisantika/springboot-adminlte3-template/blob/main/src/test/java/com/hendisantika/SpringbootAdminlte3TemplateApplicationTests.java
```java
@SpringBootTest
class SpringbootAdminlte3TemplateApplicationTests {

    @Test
    void contextLoads() {
    }

}
```
I suppose something is missing here may be bean declaration because the JUnit test is KO

Thank you very much.
Best regards,

**Comment by hendisantika** [comment]
It can skip it.

**Comment by craph** [comment]
Do you know why the actions is failing on the tests ?

**Comment by hendisantika** [comment]
Because Spring Boot can't connect to MySQL Container.

**Comment by craph** [comment]
I suppose for the test you need to have an application.properties in the path : src/test/resources  
When Spring Boot try to configure the context it will look in src/test/resources to find configuration to instanciate the database part.

**Comment by craph** [comment]
I guess this is the application.properties that is missing in src/test/ressources

**Comment by craph** [comment]
did you try to only add missing application.properties in src/test/ressources first ?

**Comment by hendisantika** [comment]
It is working now @craph. You can check it now. Thanks by the way.

**Comment by craph** [comment]
what was the issue ? the missing config file in src/test/ressources ?

**Comment by hendisantika** [comment]
Yes, it is.
