### ISSUE TITLE
User list doesn't work

### ISSUE THREAD

**Issue by craph** [hendisantika/springboot-adminlte3-template#6]
Hello,

In the file `user-list.html` there is a javascript function called `findAll` but this function calls : `http://localhost:1111/api/v1/user` but it seems the API is not implemented in the Java code base.

I can't find any RestController, api/v1 url nor port 1111 configured.

Is it normal ? If not, is it possible to add it to be able to list the user in the correct page ?

Best regards,

**Comment by hendisantika** [comment]
Yes, It is possible.

**Comment by hendisantika** [comment]
It's already implemented. Check the link
