### ISSUE TITLE
User list still doesn't work

### ISSUE THREAD

**Issue by craph** [hendisantika/springboot-adminlte3-template#7]
Hello,

I reopen another issue because there is no RestController for `api/v1`. You have changed the port to `8080` instead of `1111` I see it.

But where is the Java code base for the endpoint `api/v1/user` ? I can't see it.

Best regards,

**Comment by hendisantika** [comment]
It's already implemented. Check the menu

**Comment by craph** [comment]
Not the menu. Where is the endpoint api in Java for `api/v1` ? I can't find the corresponding Java part

**Comment by hendisantika** [comment]
Please run the application first. Then check the menu user

**Comment by craph** [comment]
> Please run the application first. Then check the menu user

After clicking in the user menu on list user link you can see in the network of your devtools of your browser this : 
```
{
    "timestamp": "2023-09-05T06:41:35.026+00:00",
    "status": 404,
    "error": "Not Found",
    "path": "/api/v1/user"
}
```

As I said earlier there are no implementation of the endpoint `/api/v1/user`

**Comment by hendisantika** [comment]
Check the video link https://www.awesomescreenshot.com/video/20494629?key=2bb9ce6683e5beaefd9d616fbbeb9515

**Comment by craph** [comment]
Please click on http://localhost:8080/user/list and then check on your devtools of your browser you will see the error because in the `user-list.html` you have this code : 
```javascript
user.findAll = function () {

                $.ajax({
                    url: "http://localhost:8080/api/v1/user",
                    type: "GET",
                    beforeSend: function (xhr) {
                        xhr.setRequestHeader("Accept", "application/json");
                        xhr.setRequestHeader("Content-Type", "application/json");
                    },
                    success: function (data) {
                        console.log(data);
                        var event_data = '';
                        $.each(data.user, function (index, value) {
                            /*console.log(value);*/
                            event_data += '<tr>';
                            event_data += '<td>' + value.name + '</td>';
                            event_data += '<td>' + value.id + '</td>';
                            event_data += '</tr>';
                        });
                        $("#list_table_json").append(event_data);

                    },
                    error: function (jqXHR, textStatus, errorThrown) {
                        var responseText = jQuery.parseJSON(jqXHR.responseText);
                        console.log(responseText);
                        console.log('Error: ' + textStatus + ' - ' + errorThrown);
                    }
                });
```

And this Javascript code is not executed correctly because the endpoint doesn't exist that's why there is a 404 error message and why on the link http://localhost:8080/user/list you are not able to see the list of the user

**Comment by hendisantika** [comment]
Ya.. It's doesn't work. Because I'm not implemented that API. I am using the user2 menu to having that.

This is just sample code.
